development: &default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  timeout: 5000

test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: <%= Integer(ENV.fetch("DB_POOL", 5)) %>
  database: db/development.sqlite3

production: &deploy
  encoding: utf8
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  url:  <%= ENV.fetch("DATABASE_URL", "") %>
